require "power-types"
require "active_support/all"
require "gemaker/version"
require "gemaker/file_utils"
require "gemaker/config"
require "gemaker/commands/base"
require "gemaker/commands/create_gem"
require "gemaker/commands/add_readme"
require "gemaker/commands/add_changelog"
require "gemaker/commands/customize_gemspec"
require "gemaker/commands/add_license"
require "gemaker/commands/add_cli_structure"
require "gemaker/commands/configure_git"
require "gemaker/commands/configure_test_env"
require "gemaker/commands/add_ruby_version"
require "gemaker/commands/customize_engine"
require "gemaker/commands/customize_rakefile"
require "gemaker/commands/customize_main_lib_file"

module Gemaker
end
