#!/usr/bin/env ruby
lib = File.expand_path(File.dirname(__FILE__) + "/../lib")
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require "commander"
require "gemaker"
require "gemaker/cli"

Gemaker::Cli.new.run
